SELECT * FROM ProdutoVeiculos

select * from VEICULO_ENTRADA
select * from VEICULO_DEVOLUCAO
select * from VEICULO_SAIDA

update VEICULO_ENTRADA set ID_CHASSI=1
update VEICULO_DEVOLUCAO set ID_CHASSI=1
update VEICULO_SAIDA set ID_CHASSI=1

SELECT VE.ID_ENTRADA as 'ID', DATA_ENTRADA_ESTOQUE AS 'DATA', CHAVE_NOTA_FISCAL AS 'CHAVE', KM_HODOMETRO AS 'HODOMETRO', VALOR_COMPRA AS 'VALOR', 'ENTRADA' TIPO FROM VEICULO_ENTRADA AS VE INNER JOIN ProdutoVeiculos AS PV ON VE.ID_CHASSI=PV.Id 
WHERE PV.Chassi = '333226' 
UNION 
SELECT VD.ID_DEVOLUCAO as 'ID', DATA_DEVOLUCAO AS 'DATA', CHAVE_NOTA_FISCAL_DEVOLUCAO AS 'CHAVE', 0, 0, 'DEVOLUCAO' TIPO FROM VEICULO_DEVOLUCAO AS VD INNER JOIN ProdutoVeiculos AS PV ON VD.ID_CHASSI=PV.Id 
WHERE PV.Chassi = '333226' 
UNION 
SELECT VS.ID_SAIDA as 'ID', DATA_VENDA AS 'DATA', CHAVE_NOTA_FISCAL_SAIDA AS 'CHAVE', 0, VALOR_VENDA AS 'VALOR', 'SAIDA' TIPO FROM VEICULO_SAIDA AS VS INNER JOIN ProdutoVeiculos AS PV ON VS.ID_CHASSI = PV.Id 
WHERE PV.Chassi = '333226' 
ORDER BY TIPO