USE Varejo2

--Adicionar na tabela PRODUTOVEICULOS a Chave Primaria do campo ID

SELECT * FROM PRODUTOVEICULOS

USE [Varejo2]
GO

INSERT INTO [dbo].[ProdutoVeiculos]
           ([idProduto]
           ,[idPedido]
           ,[Chassi]
           ,[Serie]
           ,[Potencia]
           ,[CapacidadeTracao]
           ,[TipoCombustivel]
           ,[CodMarcaModelo]
           ,[CodCorDetran]
           ,[EspecieVeiculo]
           ,[Restricao]
           ,[CondicaoVeiculo]
           ,[NumeroMotor]
           ,[Cilindradas]
           ,[PesoLiq]
           ,[PesoBruto]
           ,[DistanciaEntreEixos]
           ,[TipodeVeiculo]
           ,[TipoDePintura]
           ,[AnoFabricacao]
           ,[AnoModeloFabricacao]
           ,[CodigdoCorMontador]
           ,[DescricaoCor]
           ,[Lotacao]
           ,[TipoOperacao])
     VALUES
           (1, 11, 333229, 'tyh8965df', 333333333, 7, 0, 1, 25699, 1, 2, 0, 0, '1273332268', 70, 0, 0, 2, 0, 2022, 2022, 'MM', 'AMARELA', 2, 3)
GO

select id, Chassi from ProdutoVeiculos where Chassi<>''

SELECT CHASSI FROM PRODUTOVEICULOS

SELECT * FROM VEICULO_ENTRADA
SELECT * FROM VEICULO_DEVOLUCAO
SELECT * FROM VEICULO_SAIDA

-- SELECT * FROM PRODUTOVEICULOS WHERE CHASSI = ''

CREATE TABLE VEICULO_ENTRADA (
	ID_ENTRADA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ID_CHASSI INT NOT NULL,
	CONSTRAINT FK_ENTRADA_PRODUTO_VEICULOS FOREIGN KEY (ID_CHASSI) REFERENCES PRODUTOVEICULOS (ID),
	KM_HODOMETRO INT,
	DATA_HORA_MEDICAO_HODOMETRO DATETIME,
	DATA_ENTRADA_ESTOQUE DATETIME,
	CHAVE_NOTA_FISCAL VARCHAR(44),
	VALOR_COMPRA DECIMAL(12,2),
	STATUS_ENVIO INT DEFAULT(0) 
)

CREATE TABLE VEICULO_DEVOLUCAO (
	ID_DEVOLUCAO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ID_CHASSI INT,
	CONSTRAINT FK_DEVOLUCAO_PRODUTO_VEICULOS FOREIGN KEY (ID_CHASSI) REFERENCES PRODUTOVEICULOS (ID),
	ID_ESTOQUE BIGINT,
	CHAVE_NOTA_FISCAL_DEVOLUCAO VARCHAR(44),
	DATA_DEVOLUCAO DATETIME,
	MOTIVO_DEVOLUCAO_MONTADORA VARCHAR(55),
	STATUS_ENVIO INT DEFAULT(0)
)

CREATE TABLE VEICULO_SAIDA (
	ID_SAIDA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ID_CHASSI INT,
	CONSTRAINT FK_SAIDA_PRODUTO_VEICULOS FOREIGN KEY (ID_CHASSI) REFERENCES PRODUTOVEICULOS (ID),
	NOME_COMPRADOR VARCHAR(40),
	EMAIL_COMPRADOR VARCHAR(40),
	TIPO_DOCUMENTO CHAR(4),
	NUMERO_DOCUMENTO VARCHAR(15),
	CEP VARCHAR(8),
	LOGRADOURO VARCHAR(30),
	NUMERO VARCHAR(5),
	COMPLEMENTO VARCHAR(20),
	BAIRRO VARCHAR(20),
	ESTADO VARCHAR(25),
	CIDADE VARCHAR(50),
	CODIGO_MUNICIPIO INT,
	ID_ESTOQUE BIGINT,
	CHAVE_NOTA_FISCAL_SAIDA VARCHAR(44),
	DATA_VENDA DATETIME,
	VALOR_VENDA DECIMAL(12,2),
	EMAIL_ESTABELECIMENTO VARCHAR(40),
	STATUS_ENVIO INT DEFAULT(0)
)